Add new URLs to ipfs.yaml
opensource-observer/oss-directory pull request #137
Opened 2023-11-12 15:14 UTC by mishmosh

These represent independent implementtions of the IPFS protocol

2023-11-12 19:26 UTC, ccerv1 commented
Thanks for the PR! It looks like n0-computer is already in the directory. Could you remove it from the list and try again? Thank you 🙌 

```
AssertionError: Duplicates found: {
  "https://github.com/n0-computer": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/n/n0-computer.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/i/ipfs.yaml"
  ]
}
```

2023-11-12 19:28 UTC, ccerv1 requested changes
Thanks for the PR! It looks like n0-computer is already in the directory. Could you remove it from the list and try again? Thank you 🙌
```
AssertionError: Duplicates found: {
  "https://github.com/n0-computer": [
    "/home/runner/work/oss-directory/oss-directory/data/projects/n/n0-computer.yaml",
    "/home/runner/work/oss-directory/oss-directory/data/projects/i/ipfs.yaml"
  ]
}
```

2023-11-13 09:10 UTC, mishmosh commented
Removed, thank you!

2023-11-13 12:46 UTC, ccerv1 approved these changes

2023-11-13 12:47 UTC, merged