Update givestation.yaml
opensource-observer/oss-directory pull request #296
Opened 2024-05-23 14:23 UTC by MrBloomguy

2024-05-23 17:44 UTC, MrBloomguy commented
The yaml has been updated.

2024-05-23 19:18 UTC, ccerv1 requested changes

2024-05-23 19:18 UTC, ccerv1 commented on data/projects/g/givestation.yaml
> +       - address: "0xabF763013d5B2dEfcB7BEaD1342962b24828C7Cf"
Almost! The indentation for each address needs to be the same. Sorry - YAML is a finicky format.
The contents look good though :)

2024-05-27 11:49 UTC, ccerv1 commented
Closing this out. I've made the updates directly through a separate PR. Thanks again!

2024-05-27 11:49 UTC, closed without merging