Add Base-Pod Project
opensource-observer/oss-directory pull request #325
Opened 2024-06-03 18:46 UTC by HypoDrop

2024-06-04 02:49 UTC, ccerv1 requested changes
Thanks for your PR! There are several changes we'd like to request:

- [ ] Please give you file the name `base-pod-hypodropcom.yaml`. This is the convention we use for projects that are part of a larger GitHub org space. You can also update the `name` field to this value.
- [ ] The address that you listed appears to be a [contract](https://basescan.org/address/0x9f0763ddbeaf0de55ce6e13a4ed3c37e0f2445c7#code), not a deployer. Please update with the correct deployer address, ie, `0x4d7D85Df9D9Dd17c41FCcA32aA8fC49ed0D973ab`. Alternatively, you could keep the address that you have but change the `networks` to `base` and the `tags` to `contract`.

In summary, my recommendation would be:

```
version: 7
name: base-pod-hypodropcom
display_name: Base Pod
github:
  - url: https://github.com/HypoDropCom/Base-Pod
blockchain:
  - address: "0x4d7D85Df9D9Dd17c41FCcA32aA8fC49ed0D973ab"
    networks:
      - any_evm
    tags:
      - deployer
      - eoa
websites:
  - url: https://zora.co/collect/base:0x9f0763ddbeaf0de55ce6e13a4ed3c37e0f2445c7
description: Future Pod Life - a heroic unity in compact spaces, where shared strength illuminates a path to a brighter word.
social:
  twitter:
    - url: https://x.com/Hypodrop
```

2024-06-05 16:58 UTC, HypoDrop commented on data/projects/b/Base-Pod.yaml
> +    - url: https://x.com/Hypodrop
```suggestion
version: 7
name: base-pod-hypodropcom
display_name: Base Pod
github:
  - url: https://github.com/HypoDropCom/Base-Pod
blockchain:
  - address: "0x4d7D85Df9D9Dd17c41FCcA32aA8fC49ed0D973ab"
    networks:
      - any_evm
    tags:
      - deployer
      - eoa
websites:
  - url: https://zora.co/collect/base:0x9f0763ddbeaf0de55ce6e13a4ed3c37e0f2445c7
description: Future Pod Life - a heroic unity in compact spaces, where shared strength illuminates a path to a brighter word.
social:
  twitter:
    - url: https://x.com/Hypodrop
```

2024-06-05 23:35 UTC, ccerv1 requested changes
Thanks for your updates!

I noticed that each of your projects is contained in the same GitHub org (hypodropcom) and several share the same deployer address. Our validator will reject submissions that share the same deployer across projects. Instead, I would recommend merging everything into a single project file named `hypodropcom.yaml`. 

For example (this only includes two of your projects):

```
version: 7
name: hypodropcom
display_name: HypoDrop
github:
  - url: https://github.com/HypoDropCom
blockchain:
  - address: "0x777777C338d93e2C7adf08D102d45CA7CC4Ed021"
    networks:
      - any_evm
    tags:
      - deployer
      - eoa
  - address: "0xF5dd11c8394c92483D462ffE78bcD0e2A72BCb0c"
    networks:
      - any_evm
    tags:
      - deployer
      - eoa
  - address: "0xed4700171b96848282b21e9099ee9a28253cc168"
    networks:
      - zora
    tags:
      - contract
  - address: "0x5D4aA9c96c81AcbD201cF979215c72f6e5487e81"
    networks:
      - base
    tags:
      - contract
websites:
  - url: https://zora.co/collect/zora:0xed4700171b96848282b21e9099ee9a28253cc168/1
  - url: https://zora.co/collect/oeth:0x8d3e56eb51e5d139f58f6423e6fcfbbaf54cf103/1
description: Advertising Platform and Community based DAO Supporting Early NFT, Web3 Projects 
social:
  twitter:
    - url: https://x.com/Hypodrop
```

2024-06-06 11:38 UTC, ccerv1 approved these changes
Thanks for the change! This looks good. Let me try to validate the entries.

2024-06-06 11:39 UTC, ccerv1 commented
/validate 2f7d31be11e6e52156902a0bf1ff42b188e25fe4

2024-06-06 12:02 UTC, ccerv1 requested changes
Thanks. The validator failed on this address: 0x777777C338d93e2C7adf08D102d45CA7CC4Ed021
which is a Zora factory, not a deployer. Could you please remove?

2024-06-06 16:08 UTC, HypoDrop commented
/validate [4e8eb47](https://github.com/opensource-observer/oss-directory/pull/325/commits/4e8eb4711bd3d6d3cccb685f321c4cd7bd60e277)

2024-06-06 20:23 UTC, ccerv1 approved these changes
Looks good now!

2024-06-06 20:24 UTC, ccerv1 commented
/validate 4e8eb4711bd3d6d3cccb685f321c4cd7bd60e277

2024-06-06 20:30 UTC, ccerv1 commented
/validate 4e8eb4711bd3d6d3cccb685f321c4cd7bd60e277

2024-06-06 20:34 UTC, merged