Update paraswap.yaml: Adding Base
opensource-observer/oss-directory pull request #363
Opened 2024-06-06 16:23 UTC by mounibec

Adding Base

2024-06-06 20:38 UTC, ccerv1 requested changes
hi there
address looks good! 
please just add the tags below the network, eg:

```
networks:
  - base
tags:
  - contract
  - factory
```

2024-06-06 23:49 UTC, mounibec commented
> hi there address looks good! please just add the tags below the network, eg:
> 
> ```
> networks:
>   - base
> tags:
>   - contract
>   - factory
> ```

Done!

2024-06-07 00:24 UTC, ccerv1 commented on data/projects/p/paraswap.yaml
>   - address: "0x59C7C832e96D2568bea6db468C1aAdcbbDa08A52"
Sorry @mounibec - I missed this, but your need to indent the address. YAML is very fussy about indentations 😓

2024-06-07 00:24 UTC, ccerv1 requested changes
Sorry @mounibec - I missed this, but your need to indent the address. YAML is very fussy about indentations 😓

2024-06-07 00:27 UTC, mounibec commented
> Sorry @mounibec - I missed this, but your need to indent the address. YAML is very fussy about indentations 😓

Missed that too, fixed!

2024-06-07 01:21 UTC, ccerv1 approved these changes

2024-06-07 01:23 UTC, ccerv1 commented
/validate 74072f59ae54529e552023c3c5e010a0d40e0833

2024-06-07 01:25 UTC, ccerv1 commented
All good now! Merging. Thanks so much 🚀

2024-06-07 01:26 UTC, merged