chore: update wevm project
opensource-observer/oss-directory pull request #437
Opened 2024-07-17 18:08 UTC by tmm

Updated Wevm details and added packages.

2024-07-17 18:09 UTC, tmm commented on data/projects/w/wagmi-dev.yaml
>  npm:
Alphabetized these to make it easier to see what was missing. If order matters, happy to switch back and append new packages to the end.

2024-07-17 18:09 UTC, tmm commented on data/projects/w/wagmi-dev.yaml
If feasible, would be nice to switch from `wagmi-dev` to `wevm` everywhere. Happy to make those changes, just let me know!

2024-07-18 02:27 UTC, ccerv1 requested changes

2024-07-18 02:27 UTC, ccerv1 commented on data/projects/w/wagmi-dev.yaml
Hey Tom,
That would be great if you make the other changes too :)

- [ ] You need to change the project filename from `wagmi-dev.yaml` to `wevm.yaml` to match the `name` field in the YAML file. 
- [ ] You need to find-replace all the collection files that reference `wagmi-dev` as well. I see 6 from [this query](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fopensource-observer.hasura.app%2Fv1%2Fgraphql&query=query+MyQuery+%7B%0A++projects_by_collection_v1%28where%3A+%7Bproject_name%3A+%7B_eq%3A+%22wagmi-dev%22%7D%7D%29+%7B%0A++++collection_name%0A++%7D%0A%7D%0A).

Soon we're going to have all the https://ecosyste.ms/ data fully onboarded. Will be very exciting to start creating downstream impact metrics for these packages! For example, getting all the onchain users / developers / gas fees for [viem](https://packages.ecosyste.ms/registries/npmjs.org/packages/viem) etc

2024-07-19 00:17 UTC, ccerv1 approved these changes
Looks good!

2024-07-19 00:18 UTC, ccerv1 commented
/validate 42ed275681c873ed717d7841d142002eaedea531

2024-07-19 02:46 UTC, merged